[project]
name = "end-to-end-youtube-sentiment"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Cosmo29", email = "vikyathshetty2911@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
end-to-end-youtube-sentiment = "end_to_end_youtube_sentiment:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
